import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { WORLDS } from '../config/worlds.js';
import { createQuest } from '../src/missions/quest.js';
import { finaleExample } from '../src/missions/finale.js';
import { encodeAssignment } from '../src/missions/assignment.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const output=fileURLToPath(new URL('../artifacts/',import.meta.url));await mkdir(output,{recursive:true});
const url=process.env.QUEST_URL||'http://127.0.0.1:4173',browser=await chromium.launch({headless:true,channel:'chrome'}),checks=[],errors=[];
const finale=JSON.parse(await readFile(new URL('../data/mathematics/f4/finale.json',import.meta.url),'utf8'));
const example=finaleExample(finale),snap=p=>p.evaluate(()=>window.mathQuest.snapshot());
function watch(p){p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});}
async function ready(p,target=url){await p.goto(target);await p.waitForFunction(()=>window.mathQuest?.snapshot().loaded);}
async function station(p){await p.locator('#checkpoint').click();await p.locator('#interaction').click();}
async function set(p,key,value){const el=p.locator('#answer-'+key);if(await el.getAttribute('type')==='range'){const min=Number(await el.getAttribute('min')),step=Number(await el.getAttribute('step'));await el.focus();await el.press('Home');for(let i=0;i<Math.round((value-min)/step);i++)await el.press('ArrowRight');}else await el.fill(String(value));}
async function answer(p,values){for(const [key,value] of Object.entries(values))await set(p,key,value);await p.locator('#submit-answer').click();assert.match(await p.locator('#feedback').getAttribute('class'),/^feedback$/);await p.locator('#continue-challenge').click();}
async function finalRun(p,answers=example.map(d=>d.answer)){await p.locator('#start-button').click();for(const values of answers){await station(p);await answer(p,values);}}
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});watch(page);await ready(page);await page.locator('#region-button').click();assert.equal(await page.locator('#enter-finale').isDisabled(),true);assert.equal(await page.locator('#practice-finale').isEnabled(),true);await page.screenshot({path:output+'/finale-locked.png',fullPage:true});await page.locator('[data-close="region-map"]').click();
  await page.locator('#teacher-button').click();assert.equal(await page.locator('#teacher-answers li').count(),6);await page.locator('#teacher-world').selectOption('finale');assert.equal(await page.locator('#teacher-tasks').inputValue(),'5');assert.equal(await page.locator('#teacher-answers li').count(),5);await page.locator('.teacher-preview summary').click();assert.match(await page.locator('#teacher-answers').innerText(),/RM182 available/);await page.screenshot({path:output+'/finale-teacher.png',fullPage:true});await page.locator('[data-close="teacher"]').click();checks.push('Locked formal entry, separate practice entry, and connected teacher preview');
  await page.locator('#region-button').click();await page.locator('#practice-finale').click();await page.waitForFunction(()=>window.mathQuest?.snapshot().loaded&&window.mathQuest.snapshot().assignment?.world==='finale');assert.equal((await snap(page)).xp,0);assert.equal(await page.locator('#mission-list li').count(),5);await page.locator('#start-button').click();
  await station(page);await answer(page,{span:8,k:.75});assert.equal((await snap(page)).manifest.bridgeCost,80);assert.equal((await snap(page)).world.platforms.filter(p=>p.questBridge).length,16);assert.ok((await snap(page)).world.platforms.filter(p=>p.questBridge).every(p=>p.x<1100));
  await station(page);await answer(page,{x:2,y:2});assert.equal((await snap(page)).manifest.distance,32);assert.equal((await snap(page)).manifest.routeCost,30);
  await station(page);assert.match(await page.locator('#challenge-prompt').innerText(),/32 m/);await set(page,'t1',4);await set(page,'v1',5);await page.locator('#preview-action').click();const frozen=await snap(page);await page.waitForTimeout(400);assert.equal((await snap(page)).world.elapsed,frozen.world.elapsed);await page.locator('#submit-answer').click();await page.screenshot({path:output+'/finale-delivery.png',fullPage:true});await page.locator('#continue-challenge').click();assert.equal((await snap(page)).manifest.available,217);assert.deepEqual((await snap(page)).world.application.effects.map(e=>e.kind),['waypoint','cart']);checks.push('Route (2,2) drives 32 m transport, real bridge, live preview and RM217 remaining');
  await station(page);assert.match(await page.locator('#challenge-prompt').innerText(),/2 red and 2 blue/);await set(page,'conditional','3/5');await set(page,'combined','3/10');await page.locator('#submit-answer').click();assert.equal((await snap(page)).quest.completed.length,3);assert.match(await page.locator('#feedback').innerText(),/Not quite/);await page.locator('#hint-button').click();await page.locator('#challenge-language').click();assert.equal(await page.locator('#answer-conditional').inputValue(),'3/5');await page.locator('#challenge-close').click();await page.reload();await page.waitForFunction(()=>window.mathQuest?.snapshot().loaded);await page.locator('#start-button').click();await station(page);assert.equal((await snap(page)).language,'ms');assert.equal((await snap(page)).quest.sessions.risk.hints,1);await answer(page,{conditional:'2/3',combined:'1/3'});assert.deepEqual((await snap(page)).world.application.effects.map(e=>e.kind),['waypoint','cart','crystals']);checks.push('Probability follows route tokens; wrong old answers, BM, hints and drafts survive refresh');
  await station(page);assert.match(await page.locator('#challenge-prompt').innerText(),/baki RM217/);await set(page,'food',6);await set(page,'medical',4);await set(page,'lamp',4);await set(page,'saving',30);await page.locator('#submit-answer').click();assert.equal((await snap(page)).quest.completed.length,4);await answer(page,{food:3,medical:1,lamp:2,saving:70});assert.equal((await snap(page)).xp,500);assert.equal((await snap(page)).independent,3);assert.equal((await snap(page)).manifest.unallocated,27);assert.deepEqual((await snap(page)).world.application.effects.map(e=>e.kind),['waypoint','cart','crystals','camp']);await page.screenshot({path:output+'/finale-completion.png',fullPage:true});checks.push('Budget rejects overspend; final supplies, retained effects, 500 XP and supported evidence');
  await page.locator('#review-button').click();const download=page.waitForEvent('download');await page.locator('#export-progress').click();await(await download).saveAs(output+'/finale-export.json');await page.locator('[data-close="journal"]').click();await page.locator('#leave-class').click();await page.waitForFunction(()=>window.mathQuest?.snapshot().loaded&&!window.mathQuest.snapshot().assignment);assert.equal((await snap(page)).region,'quadratics');assert.equal((await snap(page)).xp,0);await page.locator('#region-button').click();assert.equal(await page.locator('#enter-finale').isDisabled(),true);assert.match(await page.locator('#finale-card .region-evidence').innerText(),/0\/5/);checks.push('Practice completion does not unlock or overwrite formal expedition progress');
  const imported=await browser.newPage();watch(imported);await ready(imported);await imported.locator('#journal-button').click();imported.once('dialog',d=>d.accept());await imported.locator('#import-file').setInputFiles(output+'/finale-export.json');await imported.waitForFunction(()=>window.mathQuest?.snapshot().loaded&&window.mathQuest.snapshot().xp===500);assert.equal((await snap(imported)).manifest.unallocated,27);assert.equal((await snap(imported)).language,'ms');assert.equal((await snap(imported)).assignment.world,'finale');checks.push('Final mission JSON import restores the connected plan into its isolated mission');
  const guided=await browser.newPage();watch(guided);const cfg={v:1,world:'finale',tasks:5,assist:true,guided:true,language:'en'};await ready(guided,url+'/?assignment='+encodeAssignment(cfg));await guided.locator('#start-button').click();await station(guided);assert.equal((await snap(guided)).quest.sessions.bridge.hints,1);await answer(guided,example[0].answer);assert.equal((await snap(guided)).independent,0);checks.push('Guided final mission automatically shows hints and preserves evidence rules');
  const chapterRegions={};
  for(const w of WORLDS){const data=JSON.parse(await readFile(new URL('../'+w.path,import.meta.url),'utf8')),q=createQuest(data),answers=w.id==='quadratics'?[{first:0,second:6},{x:3,y:9},{span:8,k:.75},{first:2,second:8},{x:5,y:9},{span:10,k:1}]:data.challenges.map(d=>d.answer);for(let i=0;i<6;i++){q.start(data.challenges[i].id);q.edit(answers[i]);assert.equal(q.submit().correct,true);}chapterRegions[w.id]={world:null,quest:q.save()};}
  const formal=await browser.newPage({viewport:{width:1440,height:1000}});watch(formal);await formal.addInitScript(regions=>{if(!sessionStorage.seeded){localStorage.setItem('mathwithcye-sunshine-quest-v1',JSON.stringify({schemaVersion:2,contentVersion:2,currentRegion:'quadratics',language:'en',assist:true,regions}));sessionStorage.seeded='yes';}},chapterRegions);await ready(formal);await formal.locator('#finish-exit').click();await formal.locator('#region-button').click();assert.equal(await formal.locator('#enter-finale').isEnabled(),true);await formal.locator('#enter-finale').click();assert.equal((await snap(formal)).assignment,null);assert.equal((await snap(formal)).region,'finale');await finalRun(formal);assert.equal((await snap(formal)).manifest.available,182);assert.equal((await snap(formal)).manifest.savings,95);assert.equal((await snap(formal)).independent,5);await formal.reload();await formal.waitForFunction(()=>window.mathQuest?.snapshot().loaded);assert.equal((await snap(formal)).xp,500);assert.equal((await snap(formal)).region,'finale');await formal.locator('#next-region').click();await formal.locator('#region-map').waitFor({state:'visible'});assert.match(await formal.locator('#course-progress').innerText(),/2250 \/ 2250/);assert.match(await formal.locator('#finale-card .region-evidence').innerText(),/500\/500 XP/);await formal.screenshot({path:output+'/finale-formal-map.png',fullPage:true});await formal.locator('[data-close="region-map"]').click();await formal.locator('#journal-button').click();await formal.locator('#restart-button').click();await formal.locator('#confirm-restart').click();assert.equal((await snap(formal)).xp,0);await formal.locator('#region-button').click();assert.equal(await formal.locator('#enter-finale').isEnabled(),true);assert.match(await formal.locator('#course-progress').innerText(),/2250 \/ 2250/);checks.push('Five validated chapters unlock formal finale; completion and restart retain chapter progress');
  const finalQ=createQuest(finale);for(const d of example){finalQ.start(d.id);finalQ.edit(d.answer);finalQ.submit();}const relock=await browser.newPage();watch(relock);const damaged={...chapterRegions,probability:{world:null,quest:{}},finale:{world:null,quest:finalQ.save()}};await relock.addInitScript(regions=>localStorage.setItem('mathwithcye-sunshine-quest-v1',JSON.stringify({schemaVersion:2,contentVersion:3,currentRegion:'finale',regions})),damaged);await ready(relock);assert.equal((await snap(relock)).region,'quadratics');checks.push('An incomplete prerequisite save cannot directly enter the formal finale');
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});watch(mobile);await ready(mobile,url+'/?assignment='+encodeAssignment({...cfg,guided:false}));assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await mobile.locator('#mission-list li').count(),5);await mobile.screenshot({path:output+'/finale-mobile-intro.png',fullPage:true});await finalRun(mobile);assert.equal(await mobile.locator('#completion').evaluate(e=>e.scrollWidth>e.clientWidth),false);await mobile.screenshot({path:output+'/finale-mobile-complete.png',fullPage:true});assert.equal((await snap(mobile)).xp,500);checks.push('Phone-sized five-stage mission, controls, ledger and complete budget flow');
  assert.deepEqual(errors,[]);const report={at:new Date().toISOString(),checks,errors,note:'Chrome desktop and mobile emulation; real devices and teacher content review pending.'};await writeFile(output+'/finale-browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
