import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {WORLDS} from '../config/worlds.js';
import {encodeAssignment,decodeAssignment,assignmentCurriculum} from '../src/missions/assignment.js';
import {readReport} from '../src/learning/class-reports.js';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true}),base=process.env.QUEST_URL||'http://127.0.0.1:4173';
const output=fileURLToPath(new URL('../artifacts/',import.meta.url));await mkdir(output,{recursive:true});
const banks=new Map(await Promise.all(WORLDS.map(async w=>[w.id,JSON.parse(await readFile(new URL('../'+w.path,import.meta.url),'utf8'))]))),checks=[],errors=[];
const snap=p=>p.evaluate(()=>window.mathQuest.snapshot());
function watch(p){p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});}
async function ready(p,url=base){await p.goto(url);await p.waitForFunction(()=>window.mathQuest?.snapshot().loaded);}
async function fill(p,values,prefix='#answer-'){
  for(const [key,value] of Object.entries(values)){const f=p.locator(prefix+key);if(await f.getAttribute('type')==='range'){const min=Number(await f.getAttribute('min')),step=Number(await f.getAttribute('step'));await f.focus();await f.press('Home');for(let i=0;i<Math.round((value-min)/step);i++)await f.press('ArrowRight');}else await f.fill(String(value));}
}
async function station(p){await p.locator('#checkpoint').click();await p.locator('#interaction').click();}
async function download(p,selector,name){const e=p.waitForEvent('download');await p.locator(selector).click();await(await e).saveAs(output+'/'+name);return readFile(output+'/'+name,'utf8');}
try{
  const p=await browser.newPage({viewport:{width:1440,height:1000}});watch(p);await ready(p);await p.locator('#teacher-button').click();await p.locator('#teacher-level').selectOption('challenge');assert.equal(await p.locator('#teacher-tasks').inputValue(),'3');assert.notEqual(await p.locator('#teacher-variant option[value="2"]').getAttribute('disabled'),null);await p.locator('#teacher-variant').selectOption('1');await p.locator('.teacher-preview summary').click();assert.match(await p.locator('#teacher-answers').innerText(),/Crossing width/);await p.locator('#generate-code').click();const code=await p.locator('#generated-code').inputValue();assert.equal(decodeAssignment(code).level,'challenge');assert.match(code,/^\d{6}$/);await p.screenshot({path:output+'/levels-teacher.png',fullPage:true});
  await p.locator('#teacher-world').selectOption('finale');assert.equal(await p.locator('#teacher-level').inputValue(),'standard');assert.equal(await p.locator('#teacher-level').isDisabled(),true);assert.equal(await p.locator('#teacher-tasks').inputValue(),'5');await p.locator('#teacher-world').selectOption('quadratics');await p.locator('#teacher-level').selectOption('foundation');await p.locator('#generate-code').click();await p.locator('#launch-class').click();await p.waitForFunction(()=>window.mathQuest?.snapshot().loaded&&window.mathQuest.snapshot().assignment?.level==='foundation');assert.match(await p.locator('#question-set').innerText(),/Foundation/);checks.push('Teacher selects real task groups, sees worked evidence, keeps six digits and cannot create unavailable finale groups');
  let solved=0;
  for(const world of WORLDS){
    for(const level of ['foundation','challenge'])for(const variant of [0,1]){
      const config={v:1,world:world.id,level,tasks:3,assist:true,guided:false,language:'en',...(variant?{variant}:{})},page=await browser.newPage();watch(page);await ready(page,base+'/?assignment='+encodeAssignment(config));await page.locator('#start-button').click();
      for(const def of assignmentCurriculum(banks.get(world.id),config).challenges){await station(page);await fill(page,def.answer);if(level==='challenge'&&def.id==='roots'){
          const extra=def.evidence[0].key;await page.locator('#answer-'+extra).fill('');await page.locator('#submit-answer').click();assert.equal((await snap(page)).quest.sessions[def.id].attempts,0);await page.locator('#answer-'+extra).fill(String(def.answer[extra]+1));await page.locator('#submit-answer').click();assert.equal((await snap(page)).xp,0);assert.match(await page.locator('#feedback').innerText(),/additional calculation/);await page.locator('#answer-'+extra).fill(String(def.answer[extra]));
        }
        await page.locator('#submit-answer').click();assert.equal(await page.locator('#feedback').getAttribute('class'),'feedback',`${world.id}/${level}/${variant}/${def.id}`);await page.locator('#continue-challenge').click();solved++;
      }
      assert.equal((await snap(page)).xp,250);assert.equal((await snap(page)).world.constructions.length,3);await page.reload();await page.waitForFunction(()=>window.mathQuest?.snapshot().loaded);assert.equal((await snap(page)).xp,250);assert.equal((await snap(page)).quest.variantId,`${level}${variant?'-b':''}-v1`);await page.close();
    }
    checks.push(`${world.id}: all 12 new task versions complete through visible controls and restore the right group`);
  }
  assert.equal(solved,60);
  const review=await browser.newPage();watch(review);const assignment={v:1,world:'quadratics',level:'challenge',tasks:3,assist:true,guided:false,language:'en'};await ready(review,base+'/?assignment='+encodeAssignment(assignment));await review.locator('#start-button').click();await station(review);await review.locator('#hint-button').click();await fill(review,{first:1,second:7,width:6});await review.locator('#submit-answer').click();await review.locator('#continue-challenge').click();await review.locator('#journal-button').click();await review.locator('#report-label').fill('LV008');await review.locator('[data-review="roots"]').click();for(const [k,v] of Object.entries({first:2,second:8,width:6}))await review.locator(`#fresh-fields [name="${k}"]`).fill(String(v));await review.locator('#fresh-submit').click();assert.match(await review.locator('#fresh-status').innerText(),/Independent/);await review.locator('#fresh-back').click();const csv=await download(review,'#export-csv','levels-report.csv');const rows=readReport(csv);assert.equal(rows.length,4);assert.equal(rows.at(-1).question_set,'challenge-b-v1');assert.equal(rows.at(-1).xp,'0');await download(review,'#export-progress','levels-progress.json');await review.locator('#restart-button').click();await review.locator('#confirm-restart').click();await review.locator('#journal-button').click();assert.equal(await review.locator('#history-count').innerText(),'1 / 20');review.once('dialog',d=>d.accept());await review.locator('#import-file').setInputFiles(output+'/levels-progress.json');await review.waitForFunction(()=>window.mathQuest?.snapshot().loaded&&window.mathQuest.snapshot().xp===75);assert.equal((await snap(review)).assignment.level,'challenge');checks.push('Challenge review checks include extra evidence, preserve group identity in CSV/JSON and archive safely on restart');
  const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});watch(phone);const finance={...assignment,world:'finance',language:'ms',variant:1};await ready(phone,base+'/?assignment='+encodeAssignment(finance));await phone.locator('#start-button').tap();await station(phone);await fill(phone,assignmentCurriculum(banks.get('finance'),finance).challenges[0].answer);assert.equal(await phone.locator('#challenge').evaluate(e=>e.scrollWidth>e.clientWidth),false);await phone.locator('#answer-shortfall').scrollIntoViewIfNeeded();await phone.screenshot({path:output+'/levels-phone.png',fullPage:true});await phone.locator('#submit-answer').tap();assert.equal((await snap(phone)).xp,75);await phone.locator('#continue-challenge').tap();await phone.locator('#teacher-button').tap();await phone.locator('#report-files').setInputFiles(output+'/levels-report.csv');await phone.waitForFunction(()=>document.getElementById('class-counts').textContent.includes('LV008'));assert.match(await phone.locator('#class-task-rows').innerText(),/Cabaran/);checks.push('Phone BM extra-answer controls and imported teacher cards identify Challenge correctly');
  assert.deepEqual(errors,[]);const result={at:new Date().toISOString(),checks,errors,newTaskVersionsSolved:solved,note:'Prototype content; independent teacher mathematics/BM review and physical device pilot still pending.'};await writeFile(output+'/levels-browser-report.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
