export default {
  tagline:'A little adventure. A different way to think.', region:'Quadratic Forest', course:'FORM 4 · MATHEMATICS', chapter:'CHAPTER 01', prototype:'PLAYABLE PROTOTYPE',
  map:'Expedition map', explore:'Explore', journal:'Learning journal', sound:'Sound', pause:'Pause', resume:'Resume adventure', paused:'Take a breath.', pausedText:'Your forest and your progress are waiting.', assist:'Adventure assistance', assistNote:'Gentler damage and travel to your current checkpoint.',
  objective:'YOUR NEXT DISCOVERY', roots:'Bridge anchors', vertex:'Highest point', design:'Living bridge', guardian:'Forest Guardian', done:'Forest restored', station:'Math station', locked:'Locked', completed:'Complete', next:'Up next', checkpoint:'Go to checkpoint', interact:'Interact', jump:'Jump', action:'Action', sword:'Solver', axe:'Collector', wood:'Materials', stone:'Crystals', xp:'XP', shields:'shields', health:'Adventure health',
  introTitle:'The forest needs\nyour kind of magic.', introText:'Three broken stations. One mysterious guardian. Use quadratic functions to bring the forest back to life.', start:'Begin expedition', continue:'Continue expedition', introNote:'No timer. Hints whenever you need them.', lesson:'Read a graph. Find its roots. Build something real.',
  moveHelp:'Move', jumpHelp:'Jump', actionHelp:'Collect / defend', interactHelp:'Math station', saveOK:'Saved on this browser', saveBad:'Saving unavailable · export your progress', saveDamaged:'An unreadable save was found. A new expedition is ready.', loading:'Opening the forest…', loadError:'Some forest assets could not load. Reload this page.',
  questLead:'Repair three stations, then release the Guardian’s three shields.', objectiveRoots:'Follow the path to the first station. Find where the arch meets the ground.', objectiveVertex:'The first gate is open. Find the highest point at the next station.', objectiveDesign:'Design an 8 m bridge with a maximum height of 12 m.', objectiveGuardian:'Cross the bridge. Apply what you learned to the Guardian’s new models.', objectiveDone:'Your expedition is complete. Open your journal to see your learning evidence.',
  challengeLabel:'FOREST FIELDWORK', guardianLabel:'GUARDIAN CHALLENGE', close:'Return to forest', blueprint:'Live blueprint', graphHelp:'Click to select coordinates, or use the fields below. Points snap to whole metres.', firstRoot:'First root x (m)', secondRoot:'Second root x (m)', vertexX:'Maximum x (m)', vertexY:'Maximum y (m)', span:'Span L (m)', scale:'Curve coefficient k', height:'Maximum height', submit:'Test my solution', hint:'Show a hint', nextHint:'Next hint', hintDone:'All hints shown', hintLabel:'FIELD NOTES', correct:'The forest responds.', incorrect:'Not quite. Try another approach.', invalid:'Enter valid numbers in both fields. Fractions such as 3/4 are welcome.', wrongRoots:'Look for both places where y = 0. The order of the roots does not matter.', wrongVertex:'Check both coordinates. The highest point lies on the axis of symmetry.', wrongDesign:'Check the span and the maximum height together. Both targets must match.', continueQuest:'Return to the trail', nextPhase:'Release the next shield', earned:'XP earned', target:'Design target', graphText:'Quadratic graph: horizontal x-axis and vertical y-axis in metres.',
  hintsAvailable:'Hints are always available. Using one does not cost a heart.', independent:'Independent first answers', journalTitle:'Your discoveries', journalText:'Adventure rewards and mathematical evidence are recorded separately.', notStarted:'Not started', working:'In practice', independentPass:'Independent first answer', supportedPass:'Completed with support / retry', attempts:'Attempts', hints:'Hints', export:'Export progress', exportNote:'This is a local prototype. Export to keep a copy; browser data can be cleared.', reset:'Start a new expedition', resetPrompt:'Start again? This replaces the expedition saved in this browser. Export a copy first if needed.', cancel:'Keep my progress', confirmReset:'Start again',
  finishedTitle:'You brought the\nforest back to life.', finishedText:'Three stations repaired. Three shields released. A new story written in mathematics.', badge:'Quadratic Explorer', badgeNote:'Adventure completion badge · not a grade or a full-chapter mastery claim.', review:'See my learning journal', finishExit:'Explore the restored forest', footer:'Made for curious minds.', source:'Adapted from Sunshine Forest', evidenceNote:'Six prototype checks only. Curriculum and BM wording await teacher review.', restored:'Station restored. Your route is open.', collectToast:'Materials collected.', rescue:'Back at camp. Your learning progress is safe.', guardianLocked:'Repair the three stations before challenging the Guardian.', needStation:'Move closer to the glowing station, then press E.', allComplete:'All stations restored. Explore or open your learning journal.', checkpointToast:'At your current checkpoint.',
  trailHome:'Base camp', trailGuardian:'Guardian', craft:'Upgrade tools', craftText:'Optional adventure upgrades using collected materials.', craftSword:'Stone solver', craftAxe:'Stone collector', craftArmor:'Wood shield', craftStoneArmor:'Stone shield', craftButton:'Make', owned:'Owned', needs:'More materials needed', workshopNote:'Learning hints and checkpoints never require materials.',
  sessionSaved:'Your draft and hints are saved when you leave.', noSelection:'No points selected yet.', stationComplete:'This station is repaired. Continue to your next objective.', activeWarning:'Complete the current station to open this route.', import:'Import progress', importInvalid:'This file is not a compatible progress save.', importConfirm:'Replace the current local expedition with this imported save?', imported:'Progress imported.'
};
