export const en={
  routePractice:'Adventure',metricruns:'Runs',metricstarted:'Started',metriccompleted:'Completed',metricindependent:'Independent',metricsupported:'Used hints',metricmissed:'Had misses',
  historyTitle:'Earlier runs',historyNote:'Up to 20 earlier runs are kept on this browser. CSV and progress exports include them. XP on the map belongs to the current run.',historyEmpty:'No earlier runs yet.',historyFull:'History is full. Export your progress, then clear earlier runs before starting again.',clearHistory:'Export and clear earlier runs',clearHistoryConfirm:'A progress backup will download before clearing earlier runs. Keep that file to recover them. Continue?',historyCleared:'Backup download requested; earlier runs cleared from this browser.',
  variantResetPrompt:'Start the next set? This run will be archived, including attempts, hints and review checks. Other routes keep their progress.',resetPrompt:'Start again? This run will be archived before a new run starts.',variantNote:'Changing sets or restarting keeps earlier evidence in your run history. Original, B and C practise the same objectives with different numbers.',
  reviewQueue:'Revisit supported answers',reviewNote:'After completing an answer with a hint or retry, try a different-number question on the same objective. Review results stay separate from the original answer and earn no extra XP. Finale reviews are not yet available.',reviewEmpty:'No completed answers need review yet.',reviewStart:'Try a fresh check',reviewResume:'Continue fresh check',reviewInput:'Enter your answer below. Graphs here are for reference.',reviewSaved:'Review saved separately. Your adventure progress is unchanged.',reviewTitle:'Fresh practice check',reviewBack:'Return to journal',
  classReports:'Class report summary',classReportsNote:'Import student-submitted CSV files locally. Files are editable; these are practice records, not verified assessment scores. Imported reports stay only in this open page. Enter a learner code before students export.',importReports:'Import student CSVs',clearReports:'Clear imported reports',exportSummary:'Export task summary',rosterLabel:'Optional roster: one learner code per line',lessonFilter:'Lesson / configuration',allLessons:'All imported reports',submitted:'Submitted learners',missingReports:'No report from',missingScope:'Missing reports are relative to the selected scope and the roster only.',reportInvalid:'Unsupported or invalid CSV. Use a game-exported report with a learner code.',reportSize:'Report limit exceeded (1 MB per file, 20 files per import, 20,000 retained rows).',reportsImported:'Reports imported. Repeated task snapshots count once; the newest export is retained.',legacyReports:'Legacy CSVs have no run IDs; repeated settings cannot distinguish older runs.',unscopedReports:'Code-only missions have no lesson identity. Use the lesson link to distinguish separate lessons.',reportCounts:'Runs / started / completed / independent / used hints / had misses',noReports:'No reports imported.',
  dueLabel:'Optional due-date / lesson label',lessonLinkNote:'The six-digit code opens the shared configuration. Use the lesson link for a separate lesson identity and due label; share that link with the whole class.',lessonIdentity:'Lesson',
  excludedBoundary:'This point is on an excluded boundary. A strict < or > inequality does not include the boundary line.',allConstraints:'This point fails at least one restriction. Check every inequality, not just one line.',bagTotal:'The numbers of red and blue crystals must add up to the stated total.',overBudget:'Purchases plus savings exceed the available budget. Check both parts of the total.',
};
export const ms={
  routePractice:'Pengembaraan',metricruns:'Pusingan',metricstarted:'Dimulakan',metriccompleted:'Selesai',metricindependent:'Kendiri',metricsupported:'Guna petunjuk',metricmissed:'Ada kesilapan',
  historyTitle:'Pusingan terdahulu',historyNote:'Sehingga 20 pusingan terdahulu disimpan dalam pelayar ini. Eksport CSV dan kemajuan merangkuminya. XP pada peta milik pusingan semasa.',historyEmpty:'Belum ada pusingan terdahulu.',historyFull:'Sejarah penuh. Eksport kemajuan, kemudian kosongkan pusingan terdahulu sebelum bermula semula.',clearHistory:'Eksport dan kosongkan pusingan terdahulu',clearHistoryConfirm:'Sandaran kemajuan akan dimuat turun sebelum pusingan terdahulu dikosongkan. Simpan fail untuk memulihkannya. Teruskan?',historyCleared:'Muat turun sandaran diminta; pusingan terdahulu dikosongkan daripada pelayar ini.',
  variantResetPrompt:'Mulakan set seterusnya? Pusingan ini akan diarkibkan termasuk cubaan, petunjuk dan semakan latihan. Laluan lain mengekalkan kemajuan.',resetPrompt:'Mulakan semula? Pusingan ini akan diarkibkan sebelum pusingan baharu bermula.',variantNote:'Menukar set atau bermula semula mengekalkan bukti terdahulu dalam sejarah. Set asal, B dan C melatih objektif sama dengan nombor berbeza.',
  reviewQueue:'Semak semula jawapan berbantuan',reviewNote:'Selepas menjawab dengan petunjuk atau cubaan semula, cuba soalan bernombor lain untuk objektif yang sama. Hasil semakan disimpan berasingan tanpa XP tambahan. Semakan finale belum tersedia.',reviewEmpty:'Belum ada jawapan lengkap yang perlu disemak.',reviewStart:'Cuba semakan baharu',reviewResume:'Sambung semakan baharu',reviewInput:'Masukkan jawapan di bawah. Graf di sini untuk rujukan.',reviewSaved:'Semakan disimpan berasingan. Kemajuan pengembaraan tidak berubah.',reviewTitle:'Semakan latihan baharu',reviewBack:'Kembali ke jurnal',
  classReports:'Ringkasan laporan kelas',classReportsNote:'Import CSV yang dihantar murid secara setempat. Fail boleh diedit; ini rekod latihan, bukan skor pentaksiran yang disahkan. Laporan import disimpan dalam halaman terbuka ini sahaja. Isi kod murid sebelum mengeksport.',importReports:'Import CSV murid',clearReports:'Kosongkan laporan import',exportSummary:'Eksport ringkasan tugasan',rosterLabel:'Senarai murid pilihan: satu kod setiap baris',lessonFilter:'Pelajaran / konfigurasi',allLessons:'Semua laporan import',submitted:'Murid menghantar',missingReports:'Tiada laporan daripada',missingScope:'Laporan belum diterima berdasarkan skop dipilih dan senarai murid sahaja.',reportInvalid:'CSV tidak disokong atau tidak sah. Gunakan laporan eksport permainan dengan kod murid.',reportSize:'Had laporan dilebihi (1 MB setiap fail, 20 fail setiap import, 20,000 baris disimpan).',reportsImported:'Laporan diimport. Salinan tugasan berulang dikira sekali; eksport terkini dikekalkan.',legacyReports:'CSV lama tiada ID pusingan; tetapan berulang tidak dapat membezakan pusingan terdahulu.',unscopedReports:'Misi kod sahaja tiada identiti pelajaran. Gunakan pautan pelajaran untuk membezakan pelajaran berasingan.',reportCounts:'Pusingan / dimulakan / selesai / kendiri / guna petunjuk / ada kesilapan',noReports:'Belum ada laporan diimport.',
  dueLabel:'Label tarikh akhir / pelajaran (pilihan)',lessonLinkNote:'Kod enam digit membuka konfigurasi bersama. Gunakan pautan pelajaran untuk identiti pelajaran dan label tarikh akhir berasingan; kongsi pautan itu dengan seluruh kelas.',lessonIdentity:'Pelajaran',
  excludedBoundary:'Titik ini berada pada sempadan yang dikecualikan. Ketaksamaan ketat < atau > tidak merangkumi garis sempadan.',allConstraints:'Titik ini tidak memenuhi sekurang-kurangnya satu syarat. Semak semua ketaksamaan, bukan satu garis sahaja.',bagTotal:'Bilangan kristal merah dan biru mesti berjumlah seperti yang dinyatakan.',overBudget:'Pembelian bersama simpanan melebihi bajet tersedia. Semak kedua-dua bahagian jumlah.',
};
