export default {
  tagline:'Pengembaraan kecil. Cara berfikir yang baharu.', region:'Hutan Kuadratik', course:'TINGKATAN 4 · MATEMATIK', chapter:'BAB 01', prototype:'PROTOTAIP BOLEH DIMAINKAN',
  map:'Peta ekspedisi', explore:'Teroka', journal:'Jurnal pembelajaran', sound:'Bunyi', pause:'Jeda', resume:'Sambung pengembaraan', paused:'Berehat sebentar.', pausedText:'Hutan dan kemajuan anda sedang menunggu.', assist:'Bantuan pengembaraan', assistNote:'Kerosakan lebih ringan dan perjalanan ke titik semak semasa.',
  objective:'PENEMUAN SETERUSNYA', roots:'Titik sauh', vertex:'Titik tertinggi', design:'Jambatan baharu', guardian:'Penjaga Hutan', done:'Hutan dipulihkan', station:'Stesen matematik', locked:'Dikunci', completed:'Selesai', next:'Seterusnya', checkpoint:'Ke titik semak', interact:'Interaksi', jump:'Lompat', action:'Tindakan', sword:'Penyelesai', axe:'Pengumpul', wood:'Bahan', stone:'Kristal', xp:'XP', shields:'perisai', health:'Kesihatan pengembaraan',
  introTitle:'Hutan memerlukan\nkeajaiban anda.', introText:'Tiga stesen rosak. Seorang penjaga misteri. Gunakan fungsi kuadratik untuk memulihkan hutan.', start:'Mulakan ekspedisi', continue:'Sambung ekspedisi', introNote:'Tiada pemasa. Petunjuk bila-bila masa.', lesson:'Baca graf. Cari punca. Bina sesuatu yang nyata.',
  moveHelp:'Bergerak', jumpHelp:'Lompat', actionHelp:'Kumpul / bertahan', interactHelp:'Stesen matematik', saveOK:'Disimpan dalam pelayar ini', saveBad:'Simpanan tidak tersedia · eksport kemajuan', saveDamaged:'Simpanan tidak dapat dibaca. Ekspedisi baharu tersedia.', loading:'Membuka hutan…', loadError:'Sesetengah aset gagal dimuatkan. Muat semula halaman.',
  questLead:'Baiki tiga stesen, kemudian lepaskan tiga perisai Penjaga.', objectiveRoots:'Ikut laluan ke stesen pertama. Cari titik lengkung pada aras tanah.', objectiveVertex:'Pintu pertama terbuka. Cari titik tertinggi di stesen seterusnya.', objectiveDesign:'Reka jambatan 8 m dengan tinggi maksimum 12 m.', objectiveGuardian:'Lintasi jambatan. Gunakan pengetahuan anda pada model baharu Penjaga.', objectiveDone:'Ekspedisi selesai. Buka jurnal untuk melihat bukti pembelajaran.',
  challengeLabel:'KERJA LAPANGAN HUTAN', guardianLabel:'CABARAN PENJAGA', close:'Kembali ke hutan', blueprint:'Pelan langsung', graphHelp:'Klik untuk memilih koordinat, atau guna ruang di bawah. Titik diselaraskan kepada meter bulat.', firstRoot:'Punca pertama x (m)', secondRoot:'Punca kedua x (m)', vertexX:'Koordinat maksimum x (m)', vertexY:'Koordinat maksimum y (m)', span:'Rentang L (m)', scale:'Pekali lengkung k', height:'Tinggi maksimum', submit:'Uji penyelesaian', hint:'Lihat petunjuk', nextHint:'Petunjuk seterusnya', hintDone:'Semua petunjuk dipaparkan', hintLabel:'NOTA LAPANGAN', correct:'Hutan memberikan respons.', incorrect:'Belum tepat. Cuba pendekatan lain.', invalid:'Masukkan nombor yang sah pada kedua-dua ruang. Pecahan seperti 3/4 dibenarkan.', wrongRoots:'Cari kedua-dua titik apabila y = 0. Susunan punca tidak penting.', wrongVertex:'Semak kedua-dua koordinat. Titik tertinggi berada pada paksi simetri.', wrongDesign:'Semak rentang dan tinggi maksimum bersama. Kedua-duanya mesti sepadan dengan sasaran.', continueQuest:'Kembali ke laluan', nextPhase:'Lepaskan perisai seterusnya', earned:'XP diperoleh', target:'Sasaran reka bentuk', graphText:'Graf kuadratik: paksi mengufuk x dan paksi mencancang y dalam meter.',
  hintsAvailable:'Petunjuk sentiasa tersedia dan tidak mengurangkan nyawa.', independent:'Jawapan pertama secara kendiri', journalTitle:'Penemuan anda', journalText:'Ganjaran pengembaraan dan bukti matematik direkodkan secara berasingan.', notStarted:'Belum bermula', working:'Sedang berlatih', independentPass:'Jawapan pertama secara kendiri', supportedPass:'Selesai dengan bantuan / cubaan semula', attempts:'Cubaan', hints:'Petunjuk', export:'Eksport kemajuan', exportNote:'Ini prototaip setempat. Eksport untuk menyimpan salinan; data pelayar boleh dipadamkan.', reset:'Mulakan ekspedisi baharu', resetPrompt:'Mula semula? Ini menggantikan ekspedisi dalam pelayar ini. Eksport salinan dahulu jika perlu.', cancel:'Kekalkan kemajuan', confirmReset:'Mula semula',
  finishedTitle:'Anda memulihkan\nkehidupan hutan.', finishedText:'Tiga stesen dibaiki. Tiga perisai dilepaskan. Kisah baharu ditulis dengan matematik.', badge:'Penjelajah Kuadratik', badgeNote:'Lencana tamat pengembaraan · bukan gred atau bukti penguasaan seluruh bab.', review:'Lihat jurnal pembelajaran', finishExit:'Teroka hutan yang dipulihkan', footer:'Untuk minda yang ingin tahu.', source:'Diadaptasi daripada Sunshine Forest', evidenceNote:'Enam semakan prototaip sahaja. Kurikulum dan bahasa BM menunggu semakan guru.', restored:'Stesen dipulihkan. Laluan terbuka.', collectToast:'Bahan dikumpulkan.', rescue:'Kembali ke kem. Kemajuan pembelajaran selamat.', guardianLocked:'Baiki tiga stesen sebelum mencabar Penjaga.', needStation:'Dekati stesen bercahaya, kemudian tekan E.', allComplete:'Semua stesen dipulihkan. Teroka atau buka jurnal.', checkpointToast:'Anda berada di titik semak semasa.',
  trailHome:'Kem asas', trailGuardian:'Penjaga', craft:'Naik taraf alat', craftText:'Naik taraf pengembaraan pilihan menggunakan bahan terkumpul.', craftSword:'Penyelesai batu', craftAxe:'Pengumpul batu', craftArmor:'Perisai kayu', craftStoneArmor:'Perisai batu', craftButton:'Buat', owned:'Dimiliki', needs:'Perlu lebih bahan', workshopNote:'Petunjuk dan titik semak tidak memerlukan bahan.',
  sessionSaved:'Draf dan petunjuk disimpan apabila anda keluar.', noSelection:'Belum ada titik dipilih.', stationComplete:'Stesen ini dibaiki. Teruskan ke objektif seterusnya.', activeWarning:'Selesaikan stesen semasa untuk membuka laluan.', import:'Import kemajuan', importInvalid:'Fail ini bukan simpanan kemajuan yang serasi.', importConfirm:'Gantikan ekspedisi setempat dengan simpanan yang diimport?', imported:'Kemajuan diimport.'
};
