const pair=(en,ms)=>({en,ms});
const world=(id,chapter,name,lesson,stations,objectives,intro,badge)=>({id,chapter,path:`data/mathematics/f4/bab${String(chapter).padStart(2,'0')}.json`,name:pair(...name),lesson:pair(...lesson),stations:stations.map(p=>pair(...p)),objectives:objectives.map(p=>pair(...p)),intro:pair(...intro),badge:pair(...badge)});
export const WORLDS=[
  world('quadratics',1,['Quadratic Forest','Hutan Kuadratik'],['Read a graph. Find its roots. Build something real.','Baca graf. Cari punca. Bina sesuatu.'],[['Bridge anchors','Tambatan jambatan'],['Highest point','Titik tertinggi'],['Living bridge','Jambatan hidup']], [['Find where the arch meets the ground.','Cari tempat lengkung menyentuh tanah.'],['Find the highest point at the next station.','Cari titik tertinggi di stesen seterusnya.'],['Design an 8 m bridge with a maximum height of 12 m.','Reka jambatan 8 m dengan tinggi maksimum 12 m.']], ['Use quadratic functions to repair three stations and release the Guardian.','Gunakan fungsi kuadratik untuk membaiki tiga stesen dan membebaskan Penjaga.'],['Quadratic Explorer','Penjelajah Kuadratik']),
  world('inequalities',6,['Inequality Canyon','Ngarai Ketaksamaan'],['Choose safe coordinates. Respect every boundary.','Pilih koordinat selamat. Patuhi setiap sempadan.'],[['Safe landing','Pendaratan selamat'],['Open boundary','Sempadan terbuka'],['Supply route','Laluan bekalan']], [['Choose a landing point inside the permitted region.','Pilih titik pendaratan dalam rantau dibenarkan.'],['A dashed boundary excludes points on the line.','Sempadan putus-putus tidak termasuk titik pada garis.'],['Choose a route that satisfies all three restrictions.','Pilih laluan yang mematuhi ketiga-tiga syarat.']], ['Choose safe landing coordinates using linear inequalities in two variables.','Pilih koordinat pendaratan selamat menggunakan ketaksamaan linear dalam dua pemboleh ubah.'],['Boundary Navigator','Pengemudi Sempadan']),
  world('motion',7,['Motion Highway','Laluan Gerakan'],['Read gradients. Use areas. Plan a delivery.','Baca kecerunan. Gunakan luas. Rancang penghantaran.'],[['Track reader','Pembaca trek'],['Distance ledger','Rekod jarak'],['Delivery cart','Troli penghantaran']], [['Read the gradient of the distance–time graph.','Baca kecerunan graf jarak–masa.'],['Find distance from the area under a speed–time graph.','Cari jarak daripada luas di bawah graf laju–masa.'],['Adjust time and speed to deliver the exact target distance.','Laras masa dan laju untuk mencapai jarak sasaran tepat.']], ['Read motion graphs and set the speed of a two-stage delivery cart.','Baca graf gerakan dan tetapkan laju troli penghantaran dua peringkat.'],['Motion Pathfinder','Penjelajah Gerakan']),
  world('probability',9,['Probability Lake','Tasik Kebarangkalian'],['Follow branches. Track replacement. Design a draw.','Ikut cabang. Jejak pengembalian. Reka cabutan.'],[['Branch explorer','Penjelajah cabang'],['Crystal draw','Cabutan kristal'],['Crystal bag','Beg kristal']], [['Calculate an independent combined event.','Kira peristiwa bergabung tak bersandar.'],['Track the changing bag after a draw without replacement.','Jejak perubahan beg selepas cabutan tanpa pengembalian.'],['Choose bag contents to match the target probability.','Pilih kandungan beg untuk sepadan dengan kebarangkalian sasaran.']], ['Use probability trees to unlock crystals. A lucky draw is never a test of understanding.','Gunakan gambar rajah pokok untuk membuka kristal. Cabutan bertuah tidak mengukur kefahaman.'],['Chance Strategist','Perancang Kebarangkalian']),
  world('finance',10,['Finance Camp','Kem Kewangan'],['Plan a budget. Save for a goal. Supply the camp.','Rancang belanjawan. Simpan untuk matlamat. Bekalkan kem.'],[['Savings target','Sasaran simpanan'],['Monthly plan','Pelan bulanan'],['Camp supplies','Bekalan kem']], [['Work out how many full months your savings goal needs.','Tentukan bilangan bulan penuh untuk sasaran simpanan.'],['Find savings after planned expenses.','Cari simpanan selepas perbelanjaan dirancang.'],['Meet the camp’s needs and savings target within the budget.','Penuhi keperluan kem dan sasaran simpanan dalam belanjawan.']], ['Make a realistic savings plan and choose camp supplies within a fixed budget.','Bina pelan simpanan dan pilih bekalan kem dalam belanjawan tetap.'],['Budget Builder','Pembina Belanjawan'])
];
export const REGIONS=[...WORLDS,FINAL_WORLD];
export const getWorld=id=>REGIONS.find(w=>w.id===id)||WORLDS[0];
export function worldText(world,key,language){
  if(world.strings?.[key])return world.strings[key][language];
  if(key==='region')return world.name[language];
  if(key==='lesson')return world.lesson[language];
  if(key==='chapter')return `${language==='ms'?'BAB':'CHAPTER'} ${String(world.chapter).padStart(2,'0')}`;
  if(key==='introText')return world.intro[language];
  if(key==='badge')return world.badge[language];
  const station=['roots','vertex','design'].indexOf(key);
  if(station>=0)return world.stations[station]?.[language];
  const objective=['objectiveRoots','objectiveVertex','objectiveDesign'].indexOf(key);
  if(objective>=0)return world.objectives?.[objective]?.[language];
}
import { FINAL_WORLD } from './finale.js';
