import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {landing,speed,distance,delivery,draw,bag,months,savings,budget} from './curriculum-templates.mjs';
const bi=(en,ms)=>({en,ms}),hint=pairs=>({en:pairs.map(p=>p[0]),ms:pairs.map(p=>p[1])});
const c=(a,b,op,n)=>({a,b,op,c:n});
const evidence=(key,en,ms,expected,rule)=>({key,label:bi(en,ms),...(rule?{rule}:{expected})});
function append(d,en,ms){d.prompt.en+=' '+en;d.prompt.ms+=' '+ms;}
function support(d,pairs,explanation){d.hints=hint(pairs);d.explanation=bi(...explanation);}
function quad(i,kind,model,title,prompt,answer,pairs,explanation,target){return {id:['roots','vertex','design'][i],station:['roots','vertex','design'][i],reward:[75,75,100][i],kind,model,title:bi(...title),prompt:bi(...prompt),answer,hints:hint(pairs),explanation:bi(...explanation),...(target?{target}:{})};}
function quadratics(level,p){
  if(level==='foundation'){
    const L=4+2*p,h=L*L/4;
    return [
      quad(0,'roots',{a:-1,b:L,c:0,domain:[0,L]},['Read the factors','Baca faktor'],[`The arch is y = x(${L} − x). At ground level, x(${L} − x) = 0. Enter the two roots in metres.`,`Lengkung ialah y = x(${L} − x). Pada aras tanah, x(${L} − x) = 0. Masukkan dua punca dalam meter.`],{first:0,second:L},[['A product is zero when either factor is zero.','Hasil darab ialah sifar apabila salah satu faktor sifar.'],[`Use x = 0 or ${L} − x = 0.`,`Gunakan x = 0 atau ${L} − x = 0.`],[`Roots: 0 and ${L}.`,`Punca: 0 dan ${L}.`]],[`The factors give anchors 0 m and ${L} m.`,`Faktor memberikan tambatan 0 m dan ${L} m.`]),
      quad(1,'vertex',{a:-1,b:L,c:0,domain:[0,L]},['Read the vertex form','Baca bentuk bucu'],[`The same arch can be written y = −(x − ${L/2})² + ${h}. Read the maximum point (x, y).`,`Lengkung yang sama boleh ditulis y = −(x − ${L/2})² + ${h}. Baca titik maksimum (x, y).`],{x:L/2,y:h},[['A square is never negative.','Kuasa dua tidak pernah negatif.'],[`The square becomes zero at x = ${L/2}.`,`Kuasa dua menjadi sifar pada x = ${L/2}.`],[`Maximum: (${L/2}, ${h}).`,`Maksimum: (${L/2}, ${h}).`]],[`The vertex form gives (${L/2}, ${h}) directly.`,`Bentuk bucu memberikan (${L/2}, ${h}) secara langsung.`]),
      quad(2,'design',{span:L,k:.5},['Complete the arch rule','Lengkapkan petua lengkung'],[`Use y = kx(L − x). Set L = ${L} m. The height rule is h = ${h}k. Choose k so h = ${h} m.`,`Gunakan y = kx(L − x). Tetapkan L = ${L} m. Petua tinggi ialah h = ${h}k. Pilih k supaya h = ${h} m.`],{span:L,k:1},[['The span L is already given.','Rentang L sudah diberi.'],[`Solve ${h}k = ${h}.`,`Selesaikan ${h}k = ${h}.`],[`Use L = ${L} and k = 1.`,`Gunakan L = ${L} dan k = 1.`]],[`The bridge has span ${L} m and height ${h} m.`,`Jambatan mempunyai rentang ${L} m dan tinggi ${h} m.`],{span:L,height:h})
    ];
  }
  const a=1+p,b=7+p,x=4+p,span=6+2*p,height=span*span/4;
  const first=quad(0,'roots',{a:-1,b:a+b,c:-a*b,domain:[a,b]},['Anchors and crossing width','Tambatan dan lebar lintasan'],[`For y = −x² + ${a+b}x − ${a*b}, find both ground anchors, then give the distance between them.`,`Bagi y = −x² + ${a+b}x − ${a*b}, cari kedua-dua tambatan tanah, kemudian beri jarak antaranya.`],{first:a,second:b,width:6},[['Set y = 0 and factorise.','Tetapkan y = 0 dan faktorkan.'],[`The factors are −(x − ${a})(x − ${b}). Width is the difference between anchors.`,`Faktornya ialah −(x − ${a})(x − ${b}). Lebar ialah beza antara tambatan.`],[`Anchors ${a}, ${b}; width ${b} − ${a} = 6 m.`,`Tambatan ${a}, ${b}; lebar ${b} − ${a} = 6 m.`]],[`The crossing is 6 m wide; its right anchor is not its width.`,`Lintasan selebar 6 m; tambatan kanan bukan lebarnya.`]);
  first.evidence=[evidence('width','Crossing width (m)','Lebar lintasan (m)',6)];
  const second=quad(1,'vertex',{a:-1,b:2*x,c:9-x*x,domain:[x-3,x+3]},['Peak and off-centre clearance','Puncak dan kelegaan luar pusat'],[`For y = −(x − ${x})² + 9, find the maximum point. A support stands at x = ${x-2}; calculate the arch height there too.`,`Bagi y = −(x − ${x})² + 9, cari titik maksimum. Penyokong berada pada x = ${x-2}; kira juga tinggi lengkung di situ.`],{x,y:9,clearance:5},[['The peak and the support are at different x-coordinates.','Puncak dan penyokong berada pada koordinat x berbeza.'],[`At x = ${x-2}, the squared term is (−2)² = 4.`,`Pada x = ${x-2}, sebutan kuasa dua ialah (−2)² = 4.`],[`Peak (${x}, 9); support height 9 − 4 = 5 m.`,`Puncak (${x}, 9); tinggi penyokong 9 − 4 = 5 m.`]],[`The maximum is 9 m, but clearance at the support is only 5 m.`,`Tinggi maksimum ialah 9 m, tetapi kelegaan di penyokong hanya 5 m.`]);
  second.evidence=[evidence('clearance','Height at the support (m)','Tinggi pada penyokong (m)',5)];
  const third=quad(2,'design',{span:4,k:.5},['Design and inspect the arch','Reka dan periksa lengkung'],[`Build y = kx(L − x) with span ${span} m and maximum height ${height} m. Then calculate its height at x = L/4.`,`Bina y = kx(L − x) dengan rentang ${span} m dan tinggi maksimum ${height} m. Kemudian kira tingginya pada x = L/4.`],{span,k:1,quarter:3*height/4},[['First satisfy the width and maximum height, then inspect another point.','Penuhi lebar dan tinggi maksimum dahulu, kemudian periksa titik lain.'],['h = kL²/4; at x = L/4, y = 3kL²/16.','h = kL²/4; pada x = L/4, y = 3kL²/16.'],[`L=${span}, k=1; quarter-span height=${3*height/4} m.`,`L=${span}, k=1; tinggi suku rentang=${3*height/4} m.`]],[`The quarter-span clearance is three quarters of the maximum height.`,`Kelegaan suku rentang ialah tiga perempat tinggi maksimum.`],{span,height});
  third.evidence=[evidence('quarter','Quarter-span height (m)','Tinggi suku rentang (m)',3*height/4)];return [first,second,third];
}
function inequalities(level,p){
  if(level==='foundation')return [
    landing(0,['One boundary','Satu sempadan'],[`Choose non-negative whole coordinates from 0 to 10 with x ≥ ${2+p}. y is unrestricted within that grid.`,`Pilih koordinat integer bukan negatif dari 0 hingga 10 dengan x ≥ ${2+p}. y bebas dalam grid itu.`],[c(1,0,'>=',2+p)],{x:2+p,y:0}),
    landing(1,['Stay below the line','Kekal di bawah garis'],[`Choose whole coordinates from 0 to 10 with y < ${4+p}. The horizontal line is excluded.`,`Pilih koordinat integer dari 0 hingga 10 dengan y < ${4+p}. Garis mengufuk tidak termasuk.`],[c(0,1,'<',4+p)],{x:1,y:3+p}),
    landing(2,['Combine two conditions','Gabungkan dua syarat'],[`Choose non-negative whole coordinates with x ≥ 1 and x + y ≤ ${6+p}.`,`Pilih koordinat integer bukan negatif dengan x ≥ 1 dan x + y ≤ ${6+p}.`],[c(1,0,'>=',1),c(1,1,'<=',6+p)],{x:2,y:2})
  ];
  return [0,1,2].map(i=>{
    const routes=i===2?[{x:5+p,y:2},{x:2+p,y:3},{x:3+p,y:3}]:[{x:2+p,y:2},{x:3+p,y:1},{x:4+p,y:3}],weights=i===2?[1,4]:i===1?[1,3]:[2,1];
    const constraints=[c(1,0,'>=',2+p),c(0,1,'>=',1),c(1,1,i===2?'<':'<=',7+p)];
    const feasible=routes.filter(r=>i!==2||r.x+r.y<7+p),cost=r=>weights[0]*r.x+weights[1]*r.y,chosen=feasible.reduce((a,b)=>cost(a)<=cost(b)?a:b);
    const d=landing(i,['Compare surveyed routes','Bandingkan laluan ditinjau'],[`Choose the cheapest permitted route from A (${routes[0].x},${routes[0].y}), B (${routes[1].x},${routes[1].y}), C (${routes[2].x},${routes[2].y}). Conditions: x ≥ ${2+p}, y ≥ 1, x+y ${i===2?'<':'≤'} ${7+p}. Route cost is RM(${weights[0]}x + ${weights[1]}y). Enter its coordinates and cost.`,`Pilih laluan dibenarkan termurah daripada A (${routes[0].x},${routes[0].y}), B (${routes[1].x},${routes[1].y}), C (${routes[2].x},${routes[2].y}). Syarat: x ≥ ${2+p}, y ≥ 1, x+y ${i===2?'<':'≤'} ${7+p}. Kos laluan ialah RM(${weights[0]}x + ${weights[1]}y). Masukkan koordinat dan kosnya.`],constraints,{...chosen,cost:cost(chosen)});
    d.decisions={routes,weights};d.evidence=[evidence('cost','Chosen route cost (RM)','Kos laluan dipilih (RM)',null,'routeCost')];
    support(d,[['First test all three surveyed points against every restriction.','Uji ketiga-tiga titik ditinjau dengan setiap syarat dahulu.'],[`Compare costs: A=${cost(routes[0])}, B=${cost(routes[1])}, C=${cost(routes[2])}; discard any excluded route.`,`Bandingkan kos: A=${cost(routes[0])}, B=${cost(routes[1])}, C=${cost(routes[2])}; ketepikan laluan yang dikecualikan.`],[`Choose (${chosen.x},${chosen.y}), RM${cost(chosen)}.`,`Pilih (${chosen.x},${chosen.y}), RM${cost(chosen)}.`]],[`Your route is feasible and cheapest among the three surveyed options.`,`Laluan anda tersaur dan termurah antara tiga pilihan ditinjau.`]);return d;
  });
}
function motion(level,p){
  if(level==='foundation'){
    const v=3+p,t=4+p,d=delivery(2,6,2,20+2*p,2,6+p);d.fields[0]={...d.fields[0],min:2,max:2,initial:2};d.controlSteps={t1:{min:2,max:2,step:1}};append(d,'The first duration is fixed at 2 s; solve only for its speed.','Tempoh pertama ditetapkan pada 2 s; cari lajunya sahaja.');
    return [speed(0,[[0,0],[t,t*v]],v),distance(1,[{duration:t,speed:v}],t*v),d];
  }
  const s=32+8*p,v=s/4,average=s/8;
  const first=speed(0,[[0,0],[2,0],[6,s],[8,s]],average);first.title=bi('Moving speed versus average speed','Laju bergerak berbanding laju purata');first.prompt=bi('Find the average speed over all 8 seconds, including rests. Also give the speed during the moving section.','Cari laju purata sepanjang 8 saat, termasuk masa pegun. Beri juga laju semasa bahagian bergerak.');first.fields[0].label=bi('Average speed (m/s)','Laju purata (m/s)');first.evidence=[evidence('moving','Moving-section speed (m/s)','Laju bahagian bergerak (m/s)',v)];first.answer.moving=v;
  support(first,[['Average speed includes all elapsed time, even rests.','Laju purata merangkumi semua masa berlalu, termasuk masa pegun.'],[`Average = ${s}/8; moving speed = ${s}/(6−2).`,`Purata = ${s}/8; laju bergerak = ${s}/(6−2).`],[`Average ${average} m/s; moving speed ${v} m/s.`,`Purata ${average} m/s; laju bergerak ${v} m/s.`]],[`Rest lowers the whole-journey average below the moving speed.`,`Masa pegun menjadikan laju purata perjalanan lebih rendah daripada laju bergerak.`]);
  const total=20+8*p,second=distance(1,[{duration:4,speed:3+p},{duration:2,speed:0},{duration:4,speed:2+p}],total);second.evidence=[evidence('average','Whole-journey average (m/s)','Purata seluruh perjalanan (m/s)',total/10)];second.answer.average=total/10;append(second,'Also calculate the average speed for the whole 10 seconds.','Kira juga laju purata untuk seluruh 10 saat.');second.hints.en[2]=`Distance = ${total} m; average = ${total}/10 = ${total/10} m/s.`;second.hints.ms[2]=`Jarak = ${total} m; purata = ${total}/10 = ${total/10} m/s.`;second.explanation=bi(`Area gives ${total} m; divide by all 10 seconds to get ${total/10} m/s.`,`Luas memberikan ${total} m; bahagi dengan semua 10 saat untuk mendapat ${total/10} m/s.`);
  const third=delivery(2,10,2,50+10*p,p?8:6,7),cap=p?52:48,fee=p?51:47;third.decisions={deliveryBudget:cap};third.evidence=[evidence('fee','Delivery fee (RM)','Caj penghantaran (RM)',null,'deliveryFee')];third.answer.fee=fee;append(third,`Fee = RM(5v₁ + 2t₁) and must not exceed RM${cap}. Enter the fee as well.`,`Caj = RM(5v₁ + 2t₁) dan tidak boleh melebihi RM${cap}. Masukkan caj juga.`);third.hints.en[2]=`Use t₁=${p?8:6}, v₁=7; fee RM${fee}.`;third.hints.ms[2]=`Gunakan t₁=${p?8:6}, v₁=7; caj RM${fee}.`;third.explanation=bi('Both the distance and the delivery budget are satisfied.','Kedua-dua jarak dan belanjawan penghantaran dipenuhi.');return [first,second,third];
}
function probability(level,p){
  const red=3+p,blue=2+p,total=red+blue;
  if(level==='foundation')return [true,false,false].map((replace,i)=>{
    const event=i===2?'RB':'RR',num=event==='RR'?red-(replace?0:1):blue,den=total-(replace?0:1),d=draw(i,red,blue,replace,event,num/den,red/total*num/den);
    d.fields=d.fields.slice(0,1);d.answer={conditional:num/den};d.focus='conditional';d.issueCrystals=true;
    d.prompt=bi(`A bag has ${red} red and ${blue} blue crystals. The first draw is red, ${replace?'and it is replaced':'and it is not replaced'}. Find only the probability that the next crystal is ${event==='RR'?'red':'blue'}.`,`Beg mengandungi ${red} kristal merah dan ${blue} biru. Cabutan pertama merah, ${replace?'dan dikembalikan':'dan tidak dikembalikan'}. Cari hanya kebarangkalian kristal seterusnya ${event==='RR'?'merah':'biru'}.`);
    support(d,[[replace?'The bag is unchanged.':'Remove the first red crystal.',replace?'Beg tidak berubah.':'Keluarkan kristal merah pertama.'],[`Favourable crystals: ${num}; crystals left: ${den}.`,`Kristal dikehendaki: ${num}; baki kristal: ${den}.`],[`Probability = ${num}/${den}.`,`Kebarangkalian = ${num}/${den}.`]],[`The next-draw probability is ${num}/${den}.`,`Kebarangkalian cabutan seterusnya ialah ${num}/${den}.`]);return d;
  });
  const tasks=['RR','RB'].map((event,i)=>{
    const num=i?blue:red-1,conditional=num/(total-1),combined=red/total*conditional,withReplacement=red/total*(i?blue:red)/total,change=Math.abs(withReplacement-combined),d=draw(i,red,blue,false,event,conditional,combined);
    d.evidence=[evidence('change','Absolute probability difference','Beza mutlak kebarangkalian',change)];d.answer.change=change;append(d,`Compare with the same event WITH replacement. Give the absolute difference between the two combined probabilities.`,`Bandingkan dengan peristiwa sama DENGAN pengembalian. Beri beza mutlak antara kedua-dua kebarangkalian bergabung.`);
    d.hints.en[2]=`Without replacement: (${red}/${total})(${num}/${total-1}); with replacement: (${red}/${total})(${i?blue:red}/${total}). Subtract smaller from larger.`;d.hints.ms[2]=`Tanpa pengembalian: (${red}/${total})(${num}/${total-1}); dengan pengembalian: (${red}/${total})(${i?blue:red}/${total}). Tolak nilai kecil daripada nilai besar.`;
    d.explanation=bi(`The conditional branch is ${conditional}; combined probability ${combined}; absolute difference ${change}. Fractions are accepted.`,`Cabang bersyarat ialah ${conditional}; kebarangkalian bergabung ${combined}; beza mutlak ${change}. Pecahan diterima.`);return d;
  });
  const n=6+2*p,r=3+p,d=bag(2,n,r*(r-1)/(n*(n-1)),r);d.evidence=[evidence('cross','P(red then blue), no replacement','P(merah kemudian biru), tanpa pengembalian',null,'crossProbability')];d.answer.cross=r/n*(n-r)/(n-1);append(d,'After choosing the bag, also calculate P(red then blue without replacement).','Selepas memilih beg, kira juga P(merah kemudian biru tanpa pengembalian).');d.hints.en[2]+=` Then P(RB)=(${r}/${n})(${n-r}/${n-1}).`;d.hints.ms[2]+=` Kemudian P(MB)=(${r}/${n})(${n-r}/${n-1}).`;d.explanation=bi('Your bag meets the two-red target, and your red-then-blue calculation uses the same chosen contents.','Beg anda memenuhi sasaran dua merah, dan pengiraan merah kemudian biru menggunakan kandungan dipilih yang sama.');return [...tasks,d];
}
function finance(level,p){
  if(level==='foundation'){
    const amount=120+20*p,d=budget(2,amount,1,1,amount-65,{food:1,medical:1,lamp:1,saving:amount-65});
    for(const item of d.model.items)item.maximum=item.minimum;
    for(const f of d.fields.slice(0,3)){f.min=f.max=f.initial=1;}d.controlSteps=Object.fromEntries(d.model.items.map(i=>[i.key,{min:1,max:1,step:1}]));
    d.prompt=bi(`Buy exactly one food pack (RM20), one medical kit (RM30) and one lamp (RM15). Budget RM${amount}. Save all remaining money. Quantities are fixed; find the savings.`,`Beli tepat satu pek makanan (RM20), satu kit perubatan (RM30) dan satu lampu (RM15). Belanjawan RM${amount}. Simpan semua baki wang. Kuantiti ditetapkan; cari simpanan.`);d.explanation=bi(`Purchases cost RM65; all remaining RM${amount-65} goes to savings.`,`Pembelian berharga RM65; semua baki RM${amount-65} menjadi simpanan.`);
    return [savings(0,300+50*p,[200]),months(1,300+50*p,200,0,(100+50*p)*3),d];
  }
  const monthly=75+25*p,initial=60,goal=initial+monthly*3+20,first=months(0,400+25*p,325,initial,goal);first.evidence=[evidence('shortfall','Shortfall after one fewer month (RM)','Kekurangan selepas kurang satu bulan (RM)',20)];first.answer.shortfall=20;append(first,'Also calculate how much the savings would fall short after one fewer month than your answer.','Kira juga kekurangan simpanan selepas kurang satu bulan daripada jawapan anda.');first.hints.en[2]+=' At 3 months, savings are RM20 short.';first.hints.ms[2]+=' Selepas 3 bulan, simpanan kurang RM20.';first.explanation.en+=' Three months leave a shortfall of RM20, so rounding down would miss the goal.';first.explanation.ms+=' Tiga bulan masih kurang RM20, jadi pembundaran ke bawah tidak mencapai matlamat.';
  const second=savings(1,500+50*p,[280,90,50]),base=80+50*p,target=base+40;
  second.evidence=[evidence('cut','Smallest sufficient spending cut (RM)','Pengurangan belanja mencukupi terkecil (RM)',50)];second.answer.cut=50;append(second,`Then choose the smallest cut from RM20, RM50 or RM80 that would raise savings to at least RM${target}. Give the cut, not the new balance.`,`Kemudian pilih pengurangan terkecil daripada RM20, RM50 atau RM80 yang meningkatkan simpanan kepada sekurang-kurangnya RM${target}. Beri pengurangan, bukan baki baharu.`);second.hints.en[2]+=` Need an extra RM40; RM50 is the smallest sufficient listed cut.`;second.hints.ms[2]+=' Perlu tambahan RM40; RM50 ialah pengurangan tersenarai terkecil yang mencukupi.';second.explanation.en+=' Of the listed cuts, RM50 is the smallest that meets the savings goal.';second.explanation.ms+=' Antara pengurangan tersenarai, RM50 ialah yang terkecil untuk mencapai sasaran simpanan.';
  const amount=180+20*p,max=amount-85,third=budget(2,amount,2,1,30,{food:2,medical:1,lamp:1,saving:max});third.decisions={maximumSaving:true};third.evidence=[evidence('minimumCost','Minimum essential spending (RM)','Belanja keperluan minimum (RM)',85)];third.answer.minimumCost=85;append(third,'Among all feasible plans, save the greatest possible amount. Also calculate the minimum total cost of essentials.','Antara semua pelan tersaur, simpan amaun paling tinggi. Kira juga jumlah kos minimum keperluan.');third.hints.en[2]=`Essentials cost 2×20 + 30 + 15 = RM85. Buy only those quantities and save RM${max}.`;third.hints.ms[2]=`Kos keperluan 2×20 + 30 + 15 = RM85. Beli kuantiti itu sahaja dan simpan RM${max}.`;third.explanation=bi(`Minimum essentials cost RM85, so maximum savings are RM${max}.`,`Kos minimum keperluan RM85, maka simpanan maksimum RM${max}.`);return [first,second,third];
}
const builders=[[1,'quadratics',quadratics],[6,'inequalities',inequalities],[7,'motion',motion],[9,'probability',probability],[10,'finance',finance]];
export async function buildLevels(){
  for(const [chapter,region,build] of builders){
    const path=new URL(`../data/mathematics/f4/bab${String(chapter).padStart(2,'0')}.json`,import.meta.url),data=JSON.parse(await readFile(path,'utf8'));
    data.levels={};
    for(const level of ['foundation','challenge']){
      const make=p=>build(level,p).map(d=>({...d,skill:`${region}-${d.kind}`,difficulty:level,reviewStatus:'awaiting-mathematics-and-BM-review',difficultyRationale:level==='foundation'?bi('Simpler representation or fewer choices; practise the prerequisite before combining decisions.','Perwakilan lebih mudah atau kurang pilihan; latih prasyarat sebelum menggabungkan keputusan.'):bi('Combine the main result with a comparison, additional condition or checking calculation.','Gabungkan hasil utama dengan perbandingan, syarat tambahan atau pengiraan semakan.'),misconceptionCodes:region==='quadratics'?(level==='foundation'?['factor-or-vertex-form-reading']:['root-versus-width','maximum-versus-point-height']):region==='inequalities'?['excluded-boundary','all-constraints','feasibility-before-cost']:region==='motion'?['gradient-versus-area','moving-versus-average-speed']:region==='probability'?['replacement-counts','branch-versus-combined']:['rounding-down','income-versus-savings','budget-constraints']}));
      data.levels[level]={variantBaseId:`${level}-v1`,challenges:make(0),variants:[{id:`${level}-b-v1`,challenges:make(1)}]};
    }
    await writeFile(path,JSON.stringify(data,null,2)+'\n');
  }
  console.log('Wrote 60 bilingual Foundation/Challenge task versions (five regions, two groups, two sets, three tasks).');
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))await buildLevels();
