import { writeFile } from 'node:fs/promises';
import { SCENARIO } from '../src/missions/finale.js';
const bi=(en,ms)=>({en,ms});
const field=(key,en,ms,range)=>({key,label:bi(en,ms),...(range?{type:'range',...range}:{type:'number'})});
const hints=rows=>({en:rows.map(r=>r[0]),ms:rows.map(r=>r[1])});
const base=(id,kind,station,gateLimit,title,prompt,notes,explanation)=>({id,kind,station,gateLimit,reward:100,title:bi(...title),prompt:bi(...prompt),hints:hints(notes),explanation:bi(...explanation)});
const tasks=[
  {...base('bridge','design','bridge',1072,['Span the supply crossing','Rentangi lintasan bekalan'],['The camp starts with RM360. Build y = kx(L − x) with span exactly 8 m and maximum height exactly 12 m. Bridge cost = RM10 per metre of span. Your design opens the supply crossing.','Kem bermula dengan RM360. Bina y = kx(L − x) dengan rentang tepat 8 m dan tinggi maksimum tepat 12 m. Kos jambatan = RM10 setiap meter rentang. Reka bentuk anda membuka lintasan bekalan.'],[['The roots are 0 and L.','Puncanya ialah 0 dan L.'],['Maximum height = kL²/4.','Tinggi maksimum = kL²/4.'],['Set L = 8 and k = 3/4. The bridge costs RM80.','Tetapkan L = 8 dan k = 3/4. Kos jambatan RM80.']],['L = 8 and k = 3/4 give maximum height 12 m. RM80 is committed to the bridge; the arch is now part of your route.','L = 8 dan k = 3/4 memberikan tinggi maksimum 12 m. RM80 diperuntukkan untuk jambatan; lengkung kini sebahagian laluan anda.']),model:{span:6,k:.5},target:{span:8,height:12},answer:{span:8,k:.75},controlSteps:{span:{min:4,max:10,step:1},k:{min:.25,max:1.5,step:.25}}},
  {...base('route','inequality','route',2062,['Mark a safe supply route','Tandakan laluan bekalan selamat'],['Choose a safe route using your bridge span. Your marker changes the route fee, journey distance and signal tokens.','Pilih laluan selamat menggunakan rentang jambatan. Penanda anda mengubah caj laluan, jarak perjalanan dan token isyarat.'],[['Substitute your coordinates into every restriction.','Gantikan koordinat ke dalam setiap syarat.'],['Solid boundaries are included. Use whole numbers and satisfy all four restrictions.','Sempadan penuh termasuk dalam rantau. Gunakan integer dan patuhi keempat-empat syarat.'],['One safe route is (3, 3). Its route fee is RM45 and delivery distance is 48 m.','Satu laluan selamat ialah (3, 3). Caj laluan RM45 dan jarak penghantaran 48 m.']],['Your marker satisfies every boundary. This selected route now sets the delivery distance, signal bag and route charge.','Penanda anda mematuhi setiap sempadan. Laluan dipilih kini menetapkan jarak penghantaran, beg isyarat dan caj laluan.']),model:{bound:10,constraints:[{a:1,b:0,op:'>=',c:2},{a:0,b:1,op:'>=',c:2},{a:1,b:1,op:'<=',c:8},{a:2,b:1,op:'<=',c:12}]},fields:[field('x','Route x','Laluan x'),field('y','Route y','Laluan y')],answer:{x:3,y:3},outputOrigin:1550},
  {...base('delivery','motion-plan','delivery',2932,['Run the supply cart','Jalankan troli bekalan'],['Program the cart for your route distance. Its fee enters the camp budget.','Atur troli untuk jarak laluan anda. Cajnya dimasukkan ke dalam belanjawan kem.'],[['Read the total area under the speed–time graph.','Baca jumlah luas di bawah graf laju–masa.'],['Distance = v₁t₁ + 2(10 − t₁).','Jarak = v₁t₁ + 2(10 − t₁).'],['The example route needs 48 m: 4 s at 9 m/s, then 6 s at 2 m/s.','Laluan contoh memerlukan 48 m: 4 s pada 9 m/s, kemudian 6 s pada 2 m/s.']],['Your plan reaches the selected route distance in 10 seconds. Its charge is reserved and the cart follows your speed graph.','Pelan anda mencapai jarak laluan dipilih dalam 10 saat. Cajnya diperuntukkan dan troli mengikuti graf laju anda.']),model:{duration:10,v2:2,maxSpeed:16},target:{distance:48},fields:[field('t1','First duration (s)','Tempoh pertama (s)',{min:1,max:9,step:1,initial:1}),field('v1','First speed (m/s)','Laju pertama (m/s)',{min:0,max:16,step:1,initial:2})],answer:{t1:4,v1:9},controlSteps:{t1:{min:1,max:9,step:1},v1:{min:0,max:16,step:1}},outputOrigin:2450},
  {...base('risk','probability-reading','risk',3412,['Calibrate the camp signal','Tentukur isyarat kem'],['Calculate the two-draw signal probability for the tokens issued by your route.','Kira kebarangkalian isyarat dua cabutan bagi token daripada laluan anda.'],[['Use the token counts from the route you chose.','Gunakan bilangan token daripada laluan dipilih.'],['Without replacement, remove the first red token.','Tanpa pengembalian, keluarkan token merah pertama.'],['For the example (3, 3), second blue is 3/5 and red then blue is 3/10.','Bagi contoh (3, 3), kedua biru ialah 3/5 dan merah kemudian biru ialah 3/10.']],['Your signal calculation matches your selected route tokens.','Pengiraan isyarat anda sepadan dengan token laluan dipilih.']),model:{red:3,blue:3,replacement:false,event:'RB'},fields:[field('conditional','P(second blue | first red)','P(kedua biru | pertama merah)'),field('combined','P(red then blue)','P(merah kemudian biru)')],answer:{conditional:3/5,combined:3/10},outputOrigin:3230,issueCrystals:true},
  {...base('budget','budget-plan','guardian',4165,['Deliver the camp essentials','Hantar keperluan asas kem'],['Supply the camp with the money left after your bridge, route and delivery.','Bekalkan kem menggunakan baki wang selepas jambatan, laluan dan penghantaran.'],[['Subtract the expedition charges before choosing supplies.','Tolak caj ekspedisi sebelum memilih bekalan.'],['Essential supplies cost RM85; protect at least RM30 savings.','Bekalan asas berharga RM85; simpan sekurang-kurangnya RM30.'],['A feasible example uses 2 food packs, 1 medical kit and 1 lamp.','Contoh sah menggunakan 2 pek makanan, 1 kit perubatan dan 1 lampu.']],['Essential supplies and savings fit the money left by your earlier decisions. Your connected expedition is complete.','Bekalan asas dan simpanan muat dalam baki wang daripada keputusan terdahulu. Ekspedisi berkaitan anda selesai.']),model:{budget:182,items:[{key:'food',name:bi('Food packs','Pek makanan'),price:20,minimum:2,maximum:6},{key:'medical',name:bi('Medical kits','Kit perubatan'),price:30,minimum:1,maximum:4},{key:'lamp',name:bi('Lamps','Lampu'),price:15,minimum:1,maximum:4}]},target:{saving:30},fields:[field('food','Food packs','Pek makanan',{min:0,max:6,step:1,initial:0}),field('medical','Medical kits','Kit perubatan',{min:0,max:4,step:1,initial:0}),field('lamp','Lamps','Lampu',{min:0,max:4,step:1,initial:0}),field('saving','Savings (RM)','Simpanan (RM)',{min:0,max:180,step:5,initial:0})],answer:{food:2,medical:1,lamp:1,saving:95},outputOrigin:3720}
];
await writeFile(new URL('../data/mathematics/f4/finale.json',import.meta.url),JSON.stringify({id:'f4-maths-final-expedition',kind:'finale',version:1,form:4,subject:'Mathematics',chapters:[1,6,7,9,10],reviewStatus:'prototype-awaiting-teacher-review',scenario:SCENARIO,challenges:tasks},null,2)+'\n');
console.log('Wrote five connected bilingual final-mission stages.');
